### PR TITLE
Change interface to prototype chain

### PR DESCRIPTION
**Pull request by An-dz**
Here's a first commit for implementing #176 

Needs a lot of more testing, I guess it also allows #106

## Todo

- [x] You've added or updated the [README.md](../blob/master/README.md) if needed
- [ ] Your code has the necessary tests written
- [ ] You have updated the [CHANGELOG.md unreleased sections](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by chrisvanmook** [comment]
@An-dz Sorry for the delay, we're going to review this ASAP!

**Comment by An-dz** [comment]
By the way, it still lacks the react hooks to control some of the features through React.

**Comment by CoenWarmer** [comment]
Any movement on this? 😬

**Comment by An-dz** [comment]
Just waiting for a green light this is what's expected then I'll finish it.

**Comment by jonkoops** [comment]
Sorry for the delay on this. I'll be available next week to take a look!

**Comment by chrisvanmook** [comment]
Hi @An-dz 

Sorry it took so long! We looked into your pull-request, however we do believe there are some issues regarding this solution that we tbh, in retrospect, could've also seen coming when opening issue #178.

1. We are forced to basically copy (a part) of the matomo's API: we need to know exactly all the options and add them into our API in order to use one. This will be very hard to maintain and will cause duplicate documentation eventually (matomo's and ours)
2. It should be possible to enable an option asynchonous, when for example fetching user info and id, then we are only able to set the ID after getting the response. This is not possible now as we need to set the userId on initialization.

I think we should make method available that can communicate directly with `window._paq`, that's also responsible of checking whether or not `window._paq` exists etc. 

I'm curious what your opinion is on this.

**Comment by An-dz** [comment]
1. Yes, it's inevitable as the list can't be obtained otherwise. That's why I wrote #174 with a specific object that allows anything, as I wrote there:

> I wrote this to be able to pass `setSecureCookie` and `setRequestMethod` and noticed that **it would not be optimal to write a specific case for each configuration** possible.

For that reason I would change the interface to this:
```js
instance
    .urlBase('https://LINK.TO.DOMAIN')
    .scriptPath('/js/matomo.js')
    .push('setSiteId', 3)
    .push('setUserId', 'example_id')
    .push('disableCookies')
    .push('setSecureCookie', true)
    .push('setRequestMethod', 'POST');
```

2. I believe the current code in this branch already allows that, I haven't tested but logically it should as the methods return the instance itself.

```js
const MatomoInstance = new window.MatomoTracker
    .default('https://localhost')
    .setSiteId(3)

MatomoInstance.initialize()
// some code to get id
MatomoInstance.setUserId(uuid)
```

**Comment by piotr-cz** [comment]
I would prefer if such methods would be optional to use.

For example I'm passing to MatomoTracker whole configuration object which is read from env file on build:
```js
const matomo = new MatomoTracker(__MATOMO__)
```

I don't have to check for optional configuration properties when some are available in ie. staging but not production
```js
const matomo = new MatomoTracker(__MATOMO__.urlBase)

if (___MATOMO___.srcUrl !== undefined) {
  matomo.setSrcUrl(__MATOMO__.srcUrl)
}
```

I mean fluent API is cool, but not for configurations.

**Comment by An-dz** [comment]
It wouldn't be a problem to implement a `init` convenience function to pass a configuration object to allow for @piotr-cz usage and still have a prototype interface for settings things after initial configuration.

**Comment by piotr-cz** [comment]
@An-dz Plus you wouldn't introduce a breaking change in API

**Comment by An-dz** [comment]
@piotr-cz I would, cause many of them are exactly problem number 1 @chrisvanmook [mentioned](https://github.com/Amsterdam/matomo-tracker/pull/178#issuecomment-664379861).

For example: `siteId`, `userId`, `linkTracking` are redundant but at the same time different from Matomo API, I would get rid of them.

**Comment by jonkoops** [comment]
I am going to close this PR for now. We're looking to introduce a new API design in the future, once the core team agrees on a strategy.

**Pull request closed without merging**
