### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by royderks**

### CODE REVIEW

**Comment by timvanoostrom** [comment]
I think the ts interface declares linktype as required. Making it optional will fix the optionality of it

**Comment by royderks** [comment]
> I think the ts interface declares linktype as required. Making it optional will fix it

Yes, I guess making `link` the default `linktype` makes sense right?

**Comment by chrisvanmook** [comment]
@royderks what's the status of this now?

**Comment by royderks** [comment]
> @royderks what's the status of this now?

This should be merged, as the function `trackLink` takes an object as argument, and not two single parameters:

```js
trackLink({ href, linkType = 'link' }) { /... }
```

**Pull request merged**
